/**
 * @agent-expo/protocol
 *
 * Shared types, schemas, and utilities for agent-expo
 */

// Types
export * from './types.js';

// Commands
export {
  // Command schemas
  Command,
  LaunchCommand,
  TerminateCommand,
  ReinstallCommand,
  SnapshotCommand,
  TapCommand,
  DoubleTapCommand,
  LongPressCommand,
  FillCommand,
  ClearCommand,
  TypeCommand,
  ScrollCommand,
  SwipeCommand,
  PinchCommand,
  NavigateCommand,
  BackCommand,
  HomeCommand,
  ReloadCommand,
  ShakeCommand,
  ScreenshotCommand,
  VisualCompareCommand,
  ScreenshotSaveCommand,
  ScreenshotCompareCommand,
  ScreenshotDiffCommand,
  ScreenshotListCommand,
  ScreenshotDeleteCommand,
  AssertCommand,
  WaitForCommand,
  NetworkRequestsCommand,
  NetworkMockCommand,
  NetworkClearMocksCommand,
  SupabaseCallsCommand,
  SupabaseClearCommand,
  ConvexCallsCommand,
  ConvexClearCommand,
  DeviceListCommand,
  DeviceInfoCommand,
  SetLocationCommand,
  SetPermissionCommand,
  KeyboardCommand,
  PressKeyCommand,
  StatusCommand,
  PingCommand,
  // Utilities
  parseCommand,
  safeParseCommand,
  // Command types (inferred from Zod schemas)
  type LaunchCommandType,
  type TerminateCommandType,
  type ReinstallCommandType,
  type SnapshotCommandType,
  type TapCommandType,
  type DoubleTapCommandType,
  type LongPressCommandType,
  type FillCommandType,
  type ClearCommandType,
  type TypeCommandType,
  type ScrollCommandType,
  type SwipeCommandType,
  type PinchCommandType,
  type NavigateCommandType,
  type BackCommandType,
  type HomeCommandType,
  type ReloadCommandType,
  type ShakeCommandType,
  type ScreenshotCommandType,
  type VisualCompareCommandType,
  type ScreenshotSaveCommandType,
  type ScreenshotCompareCommandType,
  type ScreenshotDiffCommandType,
  type ScreenshotListCommandType,
  type ScreenshotDeleteCommandType,
  type AssertCommandType,
  type WaitForCommandType,
  type NetworkRequestsCommandType,
  type NetworkMockCommandType,
  type NetworkClearMocksCommandType,
  type SupabaseCallsCommandType,
  type SupabaseClearCommandType,
  type ConvexCallsCommandType,
  type ConvexClearCommandType,
  type DeviceListCommandType,
  type DeviceInfoCommandType,
  type SetLocationCommandType,
  type SetPermissionCommandType,
  type KeyboardCommandType,
  type PressKeyCommandType,
  type StatusCommandType,
  type PingCommandType,
} from './commands.js';

// Responses
export {
  // Response utilities
  success,
  error,
  serializeResponse,
  parseResponse,
  isSuccess,
  isError,
  ErrorCode,
  // Response types
  type ErrorResponse,
  type Response,
  type LaunchResponseData,
  type TerminateResponseData,
  type SnapshotResponseData,
  type TapResponseData,
  type FillResponseData,
  type ClearResponseData,
  type ScrollResponseData,
  type SwipeResponseData,
  type NavigateResponseData,
  type BackResponseData,
  type HomeResponseData,
  type ScreenshotResponseData,
  type VisualCompareResponseData,
  type ScreenshotSaveResponseData,
  type ScreenshotCompareResponseData,
  type ScreenshotDiffResponseData,
  type ScreenshotListResponseData,
  type ScreenshotDeleteResponseData,
  type AssertResponseData,
  type WaitForResponseData,
  type NetworkRequestsResponseData,
  type NetworkMockResponseData,
  type NetworkClearMocksResponseData,
  type SupabaseCallsResponseData,
  type ConvexCallsResponseData,
  type DeviceListResponseData,
  type DeviceInfoResponseData,
  type SetLocationResponseData,
  type SetPermissionResponseData,
  type KeyboardResponseData,
  type StatusResponseData,
  type PingResponseData,
} from './responses.js';

// Errors
export { AgentExpoError, isAgentExpoError, Errors } from './errors/index.js';

// Utilities
export {
  ExponentialBackoff,
  DEFAULT_BACKOFF,
  delay,
  withBackoff,
  type BackoffConfig,
} from './utils/backoff.js';

// Logger
export {
  Logger,
  LogLevel,
  logger,
  parseLogLevel,
  getLogLevelName,
  type LoggerConfig,
} from './utils/logger.js';
